version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: workflow_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: workflow_engine
    volumes:
      - mongodb_data:/data/db
    networks:
      - workflow_network

  redis:
    image: redis:7.2-alpine
    container_name: workflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workflow_network

  api:
    build: .
    container_name: workflow_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/workflow_engine?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - mongodb
      - redis
    networks:
      - workflow_network

volumes:
  mongodb_data:
  redis_data:

networks:
  workflow_network:
    driver: bridge