# Archivo docker-compose.yml corregido
services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    container_name: workflow_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: engine_workflow
    volumes:
      - mongodb_data:/data/db
    networks:
      - workflow_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  # Cache Redis
  redis:
    image: redis:7.2-alpine
    container_name: workflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workflow_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # API Principal
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: workflow_api
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - workflow_network
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/engine_workflow?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  redis_data:

networks:
  workflow_network:
    driver: bridge