services:
  # Run Service
  mongodb:
    image: mongo:7.0
    container_name: workflow_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: engine_workflow
    volumes:
      - mongodb_data:/data/db
    networks:
      - workflow_network

  # Run Service
  redis:
    image: redis:7.2-alpine
    container_name: workflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workflow_network

  # Run Service
  api:
    build: .
    container_name: workflow_api
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
    networks:
      - workflow_network
    env_file:
      - .env

volumes:
  mongodb_data:
  redis_data:

networks:
  workflow_network:
    driver: bridge